package model

type ShopGoods struct{
	Id uint `json:"id" gorm:"primaryKey"`
	GoodsId string `json:"goodsId" gorm:"column:goodsId;comment:淘宝商品ID"`
	Title string `json:"title" gorm:"column:title;comment:淘宝标题"`
	ItemLink string `json:"itemLink" gorm:"column:itemLink;comment:商品淘宝链接"`
	Dtitle string `json:"dtitle" gorm:"column:dtitle;comment:大淘客短标题"`
	Desc string `json:"desc" gorm:"column:desc;comment:推广文案"`
	Cid uint `json:"cid" gorm:"column:cid;comment:商品在大淘客的分类id"`
	Tbcid uint `json:"tbcid" gorm:"column:tbcid;comment:商品在淘宝的分类id"`
	MainPic string `json:"mainPic" gorm:"column:mainPic;comment:商品主图链接"`
	MarketingMainPic string `json:"marketingMainPic" gorm:"column:marketingMainPic;comment:营销主图链接"`
	Video string `json:"video" gorm:"column:video;comment:商品视频"`
	OriginalPrice float32 `json:"originalPrice" gorm:"column:originalPrice;precision:8;comment:商品原价"`
	ActualPrice float32 `json:"actualPrice" gorm:"column:actualPrice;precision:8;comment:券后价"`
	Discounts float32 `json:"discounts" gorm:"column:discounts;precision:4;comment:折扣力度"`
	CommissionType uint8 `json:"commissionType" gorm:"column:commissionType;type:tinyint;comment:佣金类型，0-通用，1-定向，2-高佣，3-营销计划"`
	CommissionRate float32 `json:"commissionRate" gorm:"column:commissionRate;precision:4;comment:佣金比例"`
	CouponLink string `json:"couponLink" gorm:"column:couponLink;comment:优惠券链接"`
	CouponTotalNum uint `json:"couponTotalNum" gorm:"column:couponTotalNum;comment:券总量"`
	CouponReceiveNum uint `json:"couponReceiveNum" gorm:"column:couponReceiveNum;comment:领券量"`
	CouponEndTime string `json:"couponEndTime" gorm:"column:couponEndTime;comment:优惠券结束时间"`
	CouponStartTime string `json:"couponStartTime" gorm:"column:couponStartTime;comment:优惠券开始时间"`
	CouponPrice float32 `json:"couponPrice" gorm:"column:couponPrice;precision:6;comment:优惠券金额"`
	CouponConditions string `json:"couponConditions" gorm:"column:couponConditions;comment:优惠券使用条件"`
	MonthSales uint `json:"monthSales" gorm:"column:monthSales;type:int;comment:30天销量"`
	TwoHoursSales uint `json:"twoHoursSales" gorm:"column:twoHoursSales;type:int;comment:2小时销量"`
	DailySales uint `json:"dailySales" gorm:"column:dailySales;type:int;comment:当日销量"`
	Brand uint8 `json:"brand" gorm:"column:brand;type:tinyint;comment:是否是品牌商品"`
	BrandId uint `json:"brandId" gorm:"column:brandId;comment:品牌id"`
	BrandName string `json:"brandName" gorm:"column:brandName;comment:品牌名称"`
	CreateTime string `json:"createTime" gorm:"column:createTime;comment:商品上架时间"`
	ActivityType uint8 `json:"activityType" gorm:"column:activityType;type:tinyint;comment:活动类型，1-无活动，2-淘抢购，3-聚划算"`
	ActivityStartTime string `json:"activityStartTime" gorm:"column:activityStartTime;comment:活动开始时间"`
	ActivityEndTime string `json:"activityEndTime" gorm:"column:activityEndTime;comment:活动结束时间"`
	ShopType uint8 `json:"shopType" gorm:"column:shopType;type:tinyint;comment:店铺类型，1-天猫，0-淘宝"`
	Haitao uint8 `json:"haitao" gorm:"column:haitao;type:tinyint;comment:是否海淘，1-海淘商品，0-非海淘商品"`
	SellerId string `json:"sellerId" gorm:"column:sellerId;comment:淘宝卖家id"`
	ShopName string `json:"shopName" gorm:"column:shopName;comment:店铺名称"`
	ShopLevel uint `json:"shopLevel" gorm:"column:shopLevel;comment:淘宝店铺等级"`
	DescScore float32 `json:"descScore" gorm:"column:descScore;precision:4;comment:描述分"`
	DsrScore float32 `json:"dsrScore" gorm:"column:dsrScore;precision:4;comment:描述相符"`
	DsrPercent float32 `json:"dsrPercent" gorm:"column:dsrPercent;precision:4;comment:描述同行比"`
	ShipScore float32 `json:"shipScore" gorm:"column:shipScore;precision:4;comment:服务态度"`
	ShipPercent float32 `json:"shipPercent" gorm:"column:shipPercent;precision:4;comment:服务同行比"`
	ServiceScore float32 `json:"serviceScore" gorm:"column:serviceScore;precision:4;comment:物流同行比"`
	HotPush uint `json:"hotPush" gorm:"column:hotPush;comment:热推值"`
	TeamName string `json:"teamName" gorm:"column:teamName;comment:放单人名称"`
	QuanMLink uint `json:"quanMLink" gorm:"column:quanMLink;comment:定金，若无定金，则显示0"`
	HzQuanOver uint `json:"hzQuanOver" gorm:"column:hzQuanOver;comment:立减，若无立减金额，则显示0"`
	Yunfeixian uint8 `json:"yunfeixian" gorm:"column:yunfeixian;type:tinyint;comment:0.不包运费险 1.包运费险"`
	EstimateAmount float32 `json:"estimateAmount" gorm:"column:estimateAmount;precision:4;comment:预估淘礼金"`
	ShopLogo string `json:"shopLogo" gorm:"column:shopLogo;comment:店铺logo"`
	FreeshipRemoteDistrict uint8 `json:"freeshipRemoteDistrict" gorm:"column:freeshipRemoteDistrict;type:tinyint;comment:偏远地区包邮，1-包邮，0-否"`
	GoldSellers uint `json:"goldSellers" gorm:"column:goldSellers;comment:是否是金牌卖家，1-是，0-非金牌卖家"`
	DirectCommissionType uint8 `json:"directCommissionType" gorm:"column:directCommissionType;type:tinyint;comment:定向佣金类型，1非定向，3定向"`
	DirectCommission float32 `json:"directCommission" gorm:"column:directCommission;precision:4;comment:定向佣金"`
	DirectCommissionLink string `json:"directCommissionLink" gorm:"column:directCommissionLink;comment:定向链接"`
}